"""
Final answer generation for AI Data Analyst.

Formats authoritative database results into a concise,
human-readable answer.

Numeric facts and ordering come directly from the database
result rather than being generated by the LLM.
"""

from app.analysis.result_formatter import format_tabular_result


def generate_answer(
    question: str,
    sql: str,
    columns: list[str],
    rows: list,
) -> str:
    """
    Generate the final answer from authoritative database data.

    The SQL and question are retained in the function signature
    because they are part of the agent contract, but the final
    response is deliberately deterministic.
    """

    if not rows:
        return "No matching data was found."

    formatted_result = format_tabular_result(
        columns=columns,
        rows=rows,
    )

    return formatted_result
