"""
Python analysis tool for AI Data Analyst.

Provides controlled Pandas-based analysis
over SQL query results.

This module intentionally exposes only predefined
analysis operations. It does not execute arbitrary
Python code generated by an LLM.
"""

import pandas as pd

from app.analysis.dataframe import rows_to_dataframe


MAX_DATAFRAME_ROWS = 1000
MAX_DATAFRAME_COLUMNS = 50


def _validate_dataframe(df: pd.DataFrame) -> None:
    """
    Validate a DataFrame before analysis.
    """

    if not isinstance(df, pd.DataFrame):
        raise TypeError(
            "Analysis input must be a Pandas DataFrame."
        )

    if len(df) > MAX_DATAFRAME_ROWS:
        raise ValueError(
            f"DataFrame contains {len(df)} rows. "
            f"Maximum allowed is {MAX_DATAFRAME_ROWS}."
        )

    if len(df.columns) > MAX_DATAFRAME_COLUMNS:
        raise ValueError(
            f"DataFrame contains {len(df.columns)} columns. "
            f"Maximum allowed is {MAX_DATAFRAME_COLUMNS}."
        )

    if len(df.columns) == 0:
        raise ValueError(
            "DataFrame contains no columns."
        )


def _validate_numeric_column(
    df: pd.DataFrame,
    value_column: str,
) -> pd.Series:
    """
    Validate that a column exists and contains
    usable numeric values.
    """

    if value_column not in df.columns:
        raise ValueError(
            f"Column '{value_column}' not found. "
            f"Available columns: {list(df.columns)}"
        )

    series = pd.to_numeric(
        df[value_column],
        errors="coerce",
    )

    if series.notna().sum() == 0:
        raise ValueError(
            f"Column '{value_column}' does not contain "
            f"usable numeric values."
        )

    return series


def create_dataframe(
    columns: list[str],
    rows: list,
) -> pd.DataFrame:
    """
    Convert SQL query results into a Pandas DataFrame.
    """

    if not columns:
        raise ValueError(
            "Cannot create DataFrame without columns."
        )

    if len(columns) > MAX_DATAFRAME_COLUMNS:
        raise ValueError(
            f"SQL result contains {len(columns)} columns. "
            f"Maximum allowed is {MAX_DATAFRAME_COLUMNS}."
        )

    if len(rows) > MAX_DATAFRAME_ROWS:
        raise ValueError(
            f"SQL result contains {len(rows)} rows. "
            f"Maximum allowed is {MAX_DATAFRAME_ROWS}."
        )

    df = rows_to_dataframe(
        columns=columns,
        rows=rows,
    )

    _validate_dataframe(df)

    return df


def calculate_percentage(
    df: pd.DataFrame,
    value_column: str,
) -> pd.DataFrame:
    """
    Calculate each row's percentage contribution
    to the total of a numeric column.
    """

    _validate_dataframe(df)

    series = _validate_numeric_column(
        df=df,
        value_column=value_column,
    )

    result = df.copy()

    total = series.sum()

    if total == 0:
        result["percentage"] = 0.0
    else:
        result["percentage"] = (
            series / total * 100
        )

    return result


def calculate_summary(
    df: pd.DataFrame,
    value_column: str,
) -> dict:
    """
    Calculate basic statistical summary
    for a numeric column.
    """

    _validate_dataframe(df)

    series = _validate_numeric_column(
        df=df,
        value_column=value_column,
    )

    return {
        "count": int(series.count()),
        "sum": float(series.sum()),
        "mean": float(series.mean()),
        "min": float(series.min()),
        "max": float(series.max()),
    }
